name: 'Update'
description: 'Update action'
inputs:
  php_version:
    type: string
    default: '8.3'
  composer_version:
    type: string
    default: '2'

outputs:
  json:
    description: 'The JSON output from the update job'

runs:
  using: 'docker'
  image: "Dockerfile"
  args:
    - ${{ inputs.php_version }}
    - ${{ inputs.composer_version }}
