name: Update dependencies and create PRs with violinist.io
inputs:
  token: 
    description: A valid github token to use (for example a PAT)
    required: true
  repository: 
    description: A valid github repository
    required: true
  licence_key: 
    description: A valid violinist.io licence key
    required: true
outputs:
  json:
    description: The JSON of the update job
    value: ${{ steps.update.outputs.json }}
runs:
  using: "composite"
  steps: 
    - name: Debug
      run: echo ${{ inputs.token }}
      shell: bash
