name: Test
on:
  push:
    branches: 
      - "1.x"
  pull_request:
    branches: 
      - "1.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Verify that the Docker image for the action builds
      run: docker build . --file Dockerfile
    - name: Integration test 1
      uses: ./
