name: Update
on:
  workflow_call:
    inputs: 
      project_url: 
        required: true
        type: string
        default: ${{ github.repositoryUrl }}
      php_version:
        required: true
        type: string
        default: '8.3'
      composer_version:
        required: true
        type: string
        default: '2'
    secrets:
      user_token: 
        required: true
      licence_key: 
        required: true

jobs:
  violinist:
    name: Run update checks and create PRs
    container:
      image: ghcr.io/violinist-dev/update-check-runner:${{ inputs.php_version }}-multi-composer-${{ inputs.composer_version }}
      env:
        USER_TOKEN: ${{ secrets.user_token }}
        PROJECT_URL: ${{ inputs.project_url }}
        LICENCE_KEY: ${{ secrets.licence_key }}

    runs-on: ubuntu-latest
    steps:
      - name: Update and PR
        run: |
          php /app/runner
